<a href="https://colab.research.google.com/github/Lim-Calculus/Generative-Deep-Learning-with-TensorFlow/blob/main/Einstein_Notation_in_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
x = tf.constant([1,2,3,4], shape=(2,2))
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [2]:
xT = tf.transpose(x)
xT

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

In [4]:
tf.linalg.einsum('ij,ij->ij', x,x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [5]:
tf.square(x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [7]:
tf.linalg.einsum('ij,jk->ik', xT,x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 14],
       [14, 20]], dtype=int32)>

In [8]:
tf.linalg.einsum('ij,jk->', xT,x)

<tf.Tensor: shape=(), dtype=int32, numpy=58>